# Generated by Django 3.0.8 on 2020-08-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
